
export {macro};

const macro =
{
	VEHICLE_GET_COLUMN_DATA : 1,
	VEHICLE_FILTER_SEARCH : 2,
	VEHICLE_UPDATE_ROW : 3,
	VEHICLE_INSERT_ROW : 4,

	CLIENT_GET_COLUMN_DATA : 5,
	CLIENT_FILTER_SEARCH : 6,
	CLIENT_UPDATE_ROW : 7,
	CLIENT_INSERT_ROW : 8
};
Object.freeze(macro);

