#!/bin/sh

DEVICE=$1

ifconfig $DEVICE 0.0.0.0 2>/dev/null || {
    echo "$0 <subscriber-lan-device>"
    echo "create a vlan interface with:"
    echo "  vconfig add <interface> <vlan-id>"
    exit
}

[ -d  /opt/chilli/etc/chilli/$DEVICE ] || mkdir /opt/chilli/etc/chilli/$DEVICE

cat > /opt/chilli/etc/chilli/$DEVICE/chilli.conf <<EOF
# Generated by $0
include /opt/chilli/etc/chilli/$DEVICE/main.conf
include /opt/chilli/etc/chilli/$DEVICE/hs.conf
include /opt/chilli/etc/chilli/$DEVICE/local.conf

ipup=/opt/chilli/etc/chilli/up.sh
ipdown=/opt/chilli/etc/chilli/down.sh
EOF

cat /opt/chilli/etc/chilli/config | \
    grep -v HS_LANIF > /opt/chilli/etc/chilli/$DEVICE/config